yamllint

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -1,4 +1,5 @@
-# nodetcl/.github/workflows/codeql.yml: GitHub Actions codeql workflow for nodetcl
+---
+# nodetcl/.github/workflows/codeql.yml: GHA CodeQL workflow for nodetcl
 # For most projects, this workflow file will not need changing; you simply need
 # to commit it to your repository.
 #
@@ -31,8 +32,9 @@ jobs:
     #   - https://gh.io/recommended-hardware-resources-for-running-codeql
     #   - https://gh.io/supported-runners-and-hardware-resources
     #   - https://gh.io/using-larger-runners (GitHub.com only)
-    # Consider using larger runners or machines with greater resources for possible analysis time improvements.
-    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
+    # Consider using larger runners or machines with greater resources for
+    # possible analysis time improvements.
+    runs-on: 'ubuntu-latest'
     timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
     permissions:
       # required for all workflows
@@ -49,85 +51,101 @@ jobs:
       fail-fast: false
       matrix:
         include:
-        - language: javascript-typescript
-          build-mode: none
-        - language: python
-          build-mode: none
-        # CodeQL supports the following values keywords for 'language': 
-        # 'c-cpp', 'csharp', 'go', 'java-kotlin', 'javascript-typescript', 'python', 'ruby', 'swift'
-        # Use `c-cpp` to analyze code written in C, C++ or both
-        # Use 'java-kotlin' to analyze code written in Java, Kotlin or both
-        # Use 'javascript-typescript' to analyze code written in JavaScript, TypeScript or both
-        # To learn more about changing the languages that are analyzed or customizing the build mode for your analysis, see:
-        # https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning
-        # If you are analyzing a compiled language, you can modify the 'build-mode' for that language to customize how your codebase is analyzed, see:
-        # https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/codeql-code-scanning-for-compiled-languages
+          - language: javascript-typescript
+            build-mode: none
+          - language: python
+            build-mode: none
+            # CodeQL supports the following values keywords for 'language':
+            # 'c-cpp', 'csharp', 'go', 'java-kotlin', 'javascript-typescript',
+            # 'python', 'ruby', 'swift'
+            # Use `c-cpp` to analyze code written in C, C++, or both
+            # Use 'java-kotlin' to analyze code written in Java, Kotlin, or both
+            # Use 'javascript-typescript' to analyze code written in JavaScript,
+            # TypeScript, or both
+            # To learn more about changing the languages that are analyzed or
+            # customizing the build mode for your analysis, see:
+            # https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning
+            # If you are analyzing a compiled language, you can modify the
+            # 'build-mode' for that language to customize how your codebase is
+            # analyzed, see:
+            # https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/codeql-code-scanning-for-compiled-languages
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v4
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-    - name: Dependencies
-      if: matrix.language == 'c-cpp'
-      run: |
-        sudo apt-get -y install waffle-utils wafw00f python3-django-waffle nodejs node-gyp node-bindings node-pre-gyp v86d node-v8flags r-cran-v8 libc6-dev-amd64-cross libgcc-s1-amd64-cross libtbb-dev dejagnu hfsutils-tcltk tcl-dev tcllib tclcurl tclcl dlocate locate node-locate-character node-p-locate node-locate-path libwhereami-dev findutils libnode-dev node-devtools-protocol npm tcllib-critcl
-        npm install node-waf
-        npm install psweb-gyp || npm install v8
-        npm install v8-compile-cache-lib
+      - name: Dependencies
+        if: matrix.language == 'c-cpp'
+        run: |
+          sudo apt-get -qq update
+          sudo apt-get -y install waffle-utils wafw00f python3-django-waffle \
+            nodejs node-gyp node-bindings node-pre-gyp v86d node-v8flags \
+            r-cran-v8 libc6-dev-amd64-cross libgcc-s1-amd64-cross libtbb-dev \
+            dejagnu hfsutils-tcltk tcl-dev tcllib tclcurl tclcl dlocate \
+            locate node-locate-character node-p-locate node-locate-path \
+            libwhereami-dev findutils libnode-dev node-devtools-protocol \
+            npm tcllib-critcl
+          npm install node-waf
+          npm install psweb-gyp || npm install v8
+          npm install v8-compile-cache-lib
 
-    # Initializes the CodeQL tools for scanning.
-    - name: Initialize CodeQL
-      uses: github/codeql-action/init@v3
-      with:
-        languages: ${{ matrix.language }}
-        build-mode: ${{ matrix.build-mode }}
-        # If you wish to specify custom queries, you can do so here or in a config file.
-        # By default, queries listed here will override any specified in a config file.
-        # Prefix the list here with "+" to use these queries and those in the config file.
+      # Initializes the CodeQL tools for scanning.
+      - name: Initialize CodeQL
+        uses: github/codeql-action/init@v3
+        with:
+          languages: ${{ matrix.language }}
+          build-mode: ${{ matrix.build-mode }}
+          # If you wish to specify custom queries, you can do so here or in a
+          # config file.
+          # By default, queries listed here will override any specified in a
+          # config file.
+          # Prefix the list here with "+" to use these queries and those in the
+          # config file.
 
-        # For more details on CodeQL's query packs, refer to:
-        # https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
-        # queries: security-extended,security-and-quality
+          # For more details on CodeQL's query packs, refer to:
+          # https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
+          # queries: security-extended,security-and-quality
 
-    # If the analyze step fails for one of the languages you are analyzing with
-    # "We were unable to automatically build your code", modify the matrix above
-    # to set the build mode to "manual" for that language. Then modify this step
-    # to build your code.
-    # Command-line programs to run using the OS shell; see:
-    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
-    - name: Manual build message
-      if: matrix.build-mode == 'manual'
-      shell: bash
-      run: |
-        echo ''
-        echo 'If you are using a "manual" build mode for one or more of the' \
-          'languages you are analyzing, replace this with the commands to build' \
-          'your code, for example:'
-        echo '  make bootstrap'
-        echo '  make release'
-        exit 1
+      # If the analyze step fails for 1 of the languages you are analyzing with
+      # "We were unable to automatically build your code", then modify the
+      # matrix above to set the build mode to "manual" for that language.
+      # Then modify this step to build your code.
+      # Command-line programs to run using the OS shell; see:
+      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
+      - name: Manual build message
+        if: matrix.build-mode == 'manual'
+        shell: bash
+        run: |
+          echo ''
+          echo 'If you are using a "manual" build mode for one or more of the' \
+            'languages you are analyzing, replace this with the commands to' \
+            'build your code, for example:'
+          echo '  make bootstrap'
+          echo '  make release'
+          exit 1
 
-    - name: Perform CodeQL Analysis
-      uses: github/codeql-action/analyze@v3
-      with:
-        category: "/language:${{matrix.language}}"
+      - name: Perform CodeQL Analysis
+        uses: github/codeql-action/analyze@v3
+        with:
+          category: "/language:${{matrix.language}}"
 
-    - name: Find missing header(s)
-      if: failure()
-      run: |
-        if test -x "$(which locate)"; then \
-          which locate && (locate v8config.h || echo "unable to locate v8config.h!"); \
-        elif test -x "$(which mlocate)"; then \
-          which mlocate && mlocate v8config.h; \
-        elif test -x "$(which plocate)"; then \
-          which plocate && plocate v8config.h; \
-        elif test -x "$(which glocate)"; then \
-          which glocate && glocate v8config.h; \
-        elif test -x "$(which find)"; then \
-          which find && find / -name v8config.h -print; \
-        elif test -x "$(which gfind)"; then \
-          which gfind && gfind / -name v8config.h -print; \
-        elif test -x "$(which mdfind)"; then \
-          which mdfind && mdfind -name v8config.h; \
-        else \
-          echo "Warning: unsure how to find v8config.h!"; \
-        fi
+      - name: Find missing header(s)
+        if: failure()
+        run: |
+          if test -x "$(which locate)"; then \
+            which locate && \
+              (locate v8config.h || echo "unable to locate v8config.h!"); \
+          elif test -x "$(which mlocate)"; then \
+            which mlocate && mlocate v8config.h; \
+          elif test -x "$(which plocate)"; then \
+            which plocate && plocate v8config.h; \
+          elif test -x "$(which glocate)"; then \
+            which glocate && glocate v8config.h; \
+          elif test -x "$(which find)"; then \
+            which find && find / -name v8config.h -print; \
+          elif test -x "$(which gfind)"; then \
+            which gfind && gfind / -name v8config.h -print; \
+          elif test -x "$(which mdfind)"; then \
+            which mdfind && mdfind -name v8config.h; \
+          else \
+            echo "Warning: unsure how to find v8config.h!" >&2; \
+          fi
